data:
  preprocess: standardize
  features:
    - j_zlogz
    - j_c1_b0_mmdt
    - j_c1_b1_mmdt
    - j_c1_b2_mmdt
    - j_c2_b1_mmdt
    - j_c2_b2_mmdt
    - j_d2_b1_mmdt
    - j_d2_b2_mmdt
    - j_d2_a1_b1_mmdt
    - j_d2_a1_b2_mmdt
    - j_m2_b1_mmdt
    - j_m2_b2_mmdt
    - j_n2_b1_mmdt
    - j_n2_b2_mmdt
    - j_mass_mmdt
    - j_multiplicity

model:
